name: Analyze Trending HF Models for Azure Catalog

on:
  schedule:
    # Runs at 12:00 UTC every day
    - cron: '0 12 * * *'

jobs:
  trending-models-analysis:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install huggingface-hub datasets pandas

    - name: Run collection script
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN_TRENDING_MODELS_ANALYSIS }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: python trending_models_analysis.py hf-azure-internal/trending-models-analysis