name: Update webhook to track model deletion in Azure ML Model collection

on:
  schedule:
    # Runs at 12:00 UTC every day
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install huggingface-hub datasets

    - name: Run update webhook script
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: python update_webhook_model_deletion.py